#!/bin/bash
# cpu tools:
# 1. cpuface: select a cpu governor
# 2. Thinkpad-Fan-Control: control Thinkpad fan speed
# 3. intel-undervolt: undervolt intel CPU (works for Haswell and newer)

separator="--------------------------------"

# Check if root
! [[ "$EUID" -ne 0 ]] && printf '\e[1;41mDo not run as root!\e[0m\n' && exit 1

# cpu governor
printf "\nStarting cpuface...\n$separator\n" && cpuface

# fan control
#cd ~/ThinkPad-Fan-Control && printf "\n$separator\nStarting ThinkPad-Fan-Control...\n$separator\n" && sudo ./start.sh
# disabled by default

# undervolting
printf "\n$separator\nApplying intel-undervolt settings...\n" && sudo intel-undervolt apply && printf "\nApplied settings, showing values...\n" && sudo intel-undervolt read
read -p "Start measuring values? [Y/n]: " answer
[[ $answer = "N" || $answer = "n" ]] && echo "Not going to measure values."
[[ $answer = "Y" || $answer = "y" || $answer = "" ]] && echo "Starting to measure values..." && sudo intel-undervolt measure
